config/routes.rb
Rails.application.routes.draw do

  root 'githubs#index'

  get "/search" , to: "githubs#search" , as: 'search'

  get "/repositiry/:id" , to: "githubs#show" , as: 'repository'

  get "/user/:login", to: "githubs#user", as: 'user'

  get "/user/follow/:login", to: "githubs#follow_user", as: 'follow_user'
  get "/user/unfollow/:login", to: "githubs#unfollow_user", as: 'unfollow_user'

  get "/repositiry/follow/:repo_id", to: "githubs#follow_repo", as: 'follow_repo'
  get "/repositiry/unfollow/:repo_id", to: "githubs#unfollow_repo", as: 'unfollow_repo'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  enum kind: [:user, :repo]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/githubs_controller.rb
class GithubsController < ApplicationController

  def index
    @repo = Octokit.repo(10955751)
    @contributors = Octokit.contributors(10955751)
  end

  def search
    @repositories = Octokit.search_repositories(params[:repositories]).items.first(5)
  end

  def show
    @repo = Octokit.repo(params[:id].to_i)
    @contributors = Octokit.contributors(@repo.id)
  end

  def user
    @user = Octokit.user(params[:login])
    @favorite_user = Favorite.user.find_by(gid: @user[:login]).present?
  end

  def follow_user
    follow = Favorite.user.find_or_initialize_by(gid: params[:login])
    follow.save

    redirect_to :back
  end

  def unfollow_user
    follow = Favorite.user.find_by(gid: params[:login])
    follow.destroy if follow.present?

    redirect_to :back
  end

  def follow_repo

    follow = Favorite.repo.find_or_initialize_by(gid: params[:repo_id])
    follow.save
    redirect_to :back
  end

  def unfollow_repo
    follow = Favorite.repo.find_by(gid: params[:repo_id])
    follow.destroy if follow.present?
    redirect_to :back
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/githubs_helper.rb
module GithubsHelper

  def is_favorite_repo(id)
    Favorite.repo.find_by(gid: id).present?
  end

  def is_favorite_user(id)
    Favorite.user.find_by(gid: id).present?
  end
end

app/views/githubs/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
        <%= link_to 'MobiDev GitHub Browser', root_path, :class => "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

    <div class="col-sm-3 col-md-3">
      <%= form_tag search_path, method: :get, :class => 'navbar-form' do %>
          <div class="input-group">
            <%= text_field_tag "repositories", nil , placeholder: 'search repositories', :class => "form-control" %>
            <div class="input-group-btn">
              <%= submit_tag "Seacrh", :class => "btn btn-default" %>
            </div>
          </div>
      <% end %>
    </div>

  </div>
</nav>

app/views/githubs/index.html.erb
<div class="show_project">
  <div class="contributors">
    <div class="wrap">
      <ol>
        <% @contributors.each do |cont|%>

            <li>
              <%= link_to cont[:login], user_path([cont.login])  %>

              <% if  is_favorite_user(cont[:login])  %>
                  <%= link_to  unfollow_user_path(cont[:login]) do %>
                      <%= image_tag('Facebook_like_thumb.png',  :class => 'like') %>
                  <% end %>
              <% else %>
                  <%= link_to follow_user_path(cont[:login]) do %>
                      <%= image_tag('Not_facebook_dislike_thumbs_down.png',  :class => 'like') %>
                  <% end %>
              <% end %>
            </li>
        <% end %>

      </ol>
    </div>
  </div>


  <div class="info_project">
    <h4><%=  @repo[:full_name]  %><br></h4>
    <h4>description: <%=   @repo[:description]  %><br></h4>
    <h4>watchers: <%=  @repo[:watchers]  %><br></h4>
    <h4>forks: <%=  @repo[:forks]  %><br></h4>
    <h4>open issues: <%=  @repo[:open_issues] %><br></h4>
    <h4>homepage: <%=  @repo[:homepage]  %><br></h4>
    <h4>GitHub repo: <%=  @repo[:html_url]  %><br></h4>
    <h4>created at: <%=  @repo[:created_at] %><br></h4>
  </div>

</div>

app/views/githubs/search.html.erb
<div class="search_title">for search term "<%=params[:repositories]%>" found</div>
<% @repositories.each do  |repo| %>
    <div class="search_project">
      <ul class="hr">
        <li><%= link_to repo[:name] , repository_path(repo[:id])%></li>
        <li><%=link_to repo[:owner][:login], user_path(repo[:owner][:login]) %></li>
        <li><a href="<%= repo[:homepage]%>"><%= repo[:homepage]%></a></li>
      </ul>
      <h4><%=truncate(repo[:description], :length => 40)  %></h4>
      <ul class="hr">
        <li>forks: <%= repo[:forks]%></li>

        <li>watchers: <%= repo[:watchers]%></li>

        <% if  is_favorite_repo(repo[:id])  %>
            <%= link_to  unfollow_repo_path(repo[:id]) do %>
                <li>
                  <%= image_tag('Facebook_like_thumb.png',  :class => 'like') %>
                  <i class="fa fa-pencil-square-o"> like </i>
                </li>
            <% end %>
        <% else %>
            <%= link_to follow_repo_path(repo[:id]) do %>
                <li>
                  <%= image_tag('Not_facebook_dislike_thumbs_down.png',  :class => 'like') %>
                  <i class="fa fa-pencil-square-o">unlike</i>
                </li>
            <% end %>
        <% end %>
      </ul>
    </div>
<%end%>

app/views/githubs/show.html.erb
<div class="show_project">
  <div class="contributors">
    <div class="wrap">
      <ol>
        <% @contributors.each do |cont|%>

            <li>
              <%= link_to cont[:login], user_path([cont.login])  %>

              <% if  is_favorite_user(cont[:login])  %>
                  <%= link_to  unfollow_user_path(cont[:login]) do %>
                      <%= image_tag('Facebook_like_thumb.png',  :class => 'like') %>
                  <% end %>
              <% else %>
                  <%= link_to follow_user_path(cont[:login]) do %>
                      <%= image_tag('Not_facebook_dislike_thumbs_down.png',  :class => 'like') %>
                  <% end %>
              <% end %>
            </li>
        <% end %>

      </ol>
    </div>
  </div>


  <div class="info_project">
    <h4><%=  @repo[:full_name]  %><br></h4>
    <h4>description: <%=   @repo[:description]  %><br></h4>
    <h4>watchers: <%=  @repo[:watchers]  %><br></h4>
    <h4>forks: <%=  @repo[:forks]  %><br></h4>
    <h4>open issues: <%=  @repo[:open_issues] %><br></h4>
    <h4>homepage: <%=  @repo[:homepage]  %><br></h4>
    <h4>GitHub repo: <%=  @repo[:html_url]  %><br></h4>
    <h4>created at: <%=  @repo[:created_at] %><br></h4>
  </div>

</div>

app/views/githubs/user.html.erb
<div class="profile-block">
  <div class="panel text-center">
    <div class="user-heading"> <a href="#"><%= image_tag @user[:avatar_url] %></a>
      <h1><%= @user[:name] %></h1>
      <p><%= @user[:login] %></p>
    </div>
    <ul class="nav nav-pills nav-stacked">
      <li>company: <%= @user[:company] %></li>
      <li><i class="fa fa-pencil-square-o">blog:<a href="<%= @user[:blog] %>"> <%= @user[:blog] %></a></i></li>
      <li><i class="fa fa-usd" aria-hidden="true"></i>followers: <%= @user[:followers] %></li>
      <li><% if @favorite_user  %>
            <%= link_to  unfollow_user_path do %>
                <%= image_tag('Facebook_like_thumb.png',  :class => 'like') %>
                <i class="fa fa-pencil-square-o"> like </i>            <% end %>
        <% else %>
            <%= link_to follow_user_path do %>
                <%= image_tag('Not_facebook_dislike_thumbs_down.png',  :class => 'like') %>
                <i class="fa fa-pencil-square-o">unlike</i>
            <% end %>
        <% end %>

      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GithubBrowser</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'githubs/header' %>


<%= yield %>


</body>
</html>